### ISSUE TITLE
Changing beta to a vector

### ISSUE THREAD

**Issue by vinkamath** [PetraVidnerova/rbf_keras#1]
Hi Petra,
I'd like to extend this code such that beta is no longer a scalar. I'm trying to convert it into a radius vector with the same dimensionality as the centers. Essentially, I'm converting the gaussian exponent  from (x-c)^2/beta to (x-c)^2/r^2. 

I have modified its shape to resemble self.centers. And the definition of the RBF kernel. But I'm having issues adding the subsequent dense layer because of a dimension mismatch. 

Can you please suggest how I can go about doing this?

**Comment by PetraVidnerova** [comment]
Hi, 

  I am using beta * (x-c)^2 in my code, but this is just because I prefer multiplication instead of division (of course in my case beta must be 1/usual_beta). It does not matter, we can use the notation (x-c)^2/beta.

So if I understand correctly, you want to have separate beta_i for each x_i (x is a vector).
Isn't the problem in the order you compute it? It should be something like ((x_i-c_i)/beta_i)^2.
I also implemented rbf kernel with the mahalanobis distance, each unit has also matrix CW. If you omit
betas and have CW diagonal, you get a different radius for each dimension.
You can find the code here:
https://gist.github.com/PetraVidnerova/ee93dc552c45ba6546d92c32f5157cc5

I am not sure this is going to help or whether I understood your question correctly. Is it possible to send me your code to see what's the problem?

**Comment by vinkamath** [comment]
Thanks for the prompt response. Yes, I'm trying to effectively calculate  ((x_i-c_i)/beta_i)^2. The dimensions are as follows:
c = num_kernels x num_features
x = 1 x num_features
beta (radius) = num_kernels x num_features.

Please see the [attached code](https://github.com/PetraVidnerova/rbf_keras/files/3044674/rbf_r.zip)   where num_kernels = 2. 
I get an error "ValueError: Input 0 is incompatible with layer dense_1: expected min_ndim=2, found ndim=1" when I add the dense layer to the RBF layer.  It sounds like the RBF layer should have two outputs, but has only 1. I see that the shape of the RBF output is (2,) is when I step through the code.  So I'm not sure what I'm doing wrong.

Thanks for all the help!

**Comment by PetraVidnerova** [comment]
Hi, I hope I got it. 
The solution should be:

def call(self, x):

        C = K.expand_dims(self.centers, 0)
        X = K.expand_dims(x, 1)

        H = (X - C) / self.radii

        return K.exp( -K.sum( H*H, axis = -1))

here is the code 
[rbf_fixed.zip](https://github.com/PetraVidnerova/rbf_keras/files/3047651/rbf_fixed.zip)

**Comment by vinkamath** [comment]
Thank Petra. The code works as intended. And the explanation really helped.

**Comment by agcala** [comment]
Sorry but when I run the examples I get an error at

assert shape[1] == self.X.shape[1]
**IndexError: tuple index out of range**

This happens when trying to initialize the widths which is a one-dimensional array. Any idea of how to get around this?

**Comment by vinkamath** [comment]
Are you saying that your training data has just one sample? Even then, shape[1] would be the width of the sample. 

Can you share your modified code and the input dataset?

**Comment by PetraVidnerova** [comment]
> This happens when trying to initialize the widths which is a one-dimensional array, so there is no 
> shape[1]. Any idea of how to get around this?

Well, I am confused now, because you are speaking about widths initialization, but this 
assert shape[1] == self.X.shape[1] is part of  InitCentersRandom that is Initializer for centers. 
It is not designed for widths.  

shape refers to dimension of centers, i.e.  it should be (number_of_centers, dim_of_network_input)
X.shape refers to dimension of data, i.e.  it should be (number_of_data_points, number_of_features)

dim_of_network_input and number_of_features must be the same 

InitCentersRandom just selects random vectors from data as centers. So you can't use it for 
initialization of widths, it's something different. 

If I am wrong, please show us the complete code and data if possible. I will try to help.

**Comment by agcala** [comment]
I don't follow. I did not modify the code. I used the code in rbf_fixed.zip. The training data has nothing to do with the error as it happens when I try to initialize the layer using previously computed centers and widths.

```
    c = np.genfromtxt(path+"centers.csv", delimiter=',', skip_header=True)
    s = np.genfromtxt(path+"widths.csv", delimiter=',', skip_header=True)
    ....................
    rbflayer = RBFLayer(num_neurons,
                        c_initializer=InitCustom(c),
                        r_initializer=InitCustom(r),
                        input_shape=(784,))
```
centers.csv and widths.csv were generated on a previous run when I initialized the centers randomly. At this point the training data has not yet been processed.

**Comment by PetraVidnerova** [comment]
OK, now I understand your point. So, my previous comment is irrelevant, because the assert fails in InitCustom. The InitCustom was written by @vinkamath so maybe (s)he will reply.
The problem is that you use  simply scalar as width (simply one width for each unit), @vinkamath uses vector (for each unit one vector of radii, i.e. different radii for each dimension). Then it makes sense to check the dimensions.
However, the RBFLayer itself (after the change proposed by @vinkamath) is designed so the radii of each unit is vector (see line 41 in rbflayer.py in rbf_fixed.zip). So it is not possible to initialize it by your widths.csv. 
What is not clear for me is where you get this file widths.csv. Because this code should not produce it because it uses radii vectors.

If you want to use scalar as radii, use my original code [rbflayer.py](https://github.com/PetraVidnerova/rbf_keras/blob/master/rbflayer.py). But now I realized, that there is no way how to initialize widths from file, I will fix it asap.

**Comment by agcala** [comment]
Understood. Thank you very much for your time. I checked the file @vinkamath provided and yes it uses also a matrix for the widths/radii. Kind of a generalization of what I wanted to do but then it doesn't seem to work when the matrix is just a column vector. I may try to fix that myself.

**Comment by PetraVidnerova** [comment]
Yes, I know that the centers and widths are saved at the end of the code. 
What was surprising for me was the fact that you do not have matrix of radii in this file but only one column vector.  

Anyway, my TODO list  should include implementing initialization from file, and including the option for radii vector to the main repository.

**Comment by badaouisaad** [comment]
Dear all,, 

I was reading this very interesting discussion. Iam curious. Why have you not computed the betas (or  radii) using the standard deviations of the points belonging to the cluster?

Correct me if i am wrong as I am no way as technical as you guys but my understanding is that there are two approaches we can take: set the standard deviation to be that of the points assigned to a particular cluster (clusters being computed with k-means) or we can use a single standard deviation for all clusters (which i believe is the original approach suggested by Petra Vidnerova).  Why uploading radii using csv and not computing them internally?  Thank you very much

**Comment by Rafael-python** [comment]
Dear
When I use rbf_fixed.zip I have this error:
ValueError: Input 0 of layer dense_19 is incompatible with the layer: : expected min_ndim=2, found ndim=1. Full shape received: (None,)

Thanks in advance

**Comment by Rafael-python** [comment]
Dear
When I use rbf_fixed.zip I have this error:
ValueError: Input 0 of layer dense_19 is incompatible with the layer: : expected min_ndim=2, found ndim=1. Full shape received: (None,)

Thanks in advance
