### ISSUE TITLE
Clustering for centers and Optimizer for hidden to output layer weight learning

### ISSUE THREAD

**Issue by parthbkgadoya** [PetraVidnerova/rbf_keras#5]
1. For computing weights between input layer and hidden layer, using K-Means clustering is preferable or not? Reference: https://www.hackerearth.com/blog/uncategorized/radial-basis-function-network/ Please give suggestion on what should be standard approach to compute these weights?

2. I want to use LBFGS optimization technique for computing weights between hidden layer and output layer? How to do this using Keras library? Any inputs would be helpful. Reference: https://en.wikipedia.org/wiki/Limited-memory_BFGS

Thanks.

**Comment by PetraVidnerova** [comment]
Thanks for your interest.

**Question 1**:  From my experience, I prefer using KMeans for RBF centres setup.  More advanced clustering algorithms would be overkill, but using clustering instead of just random samples usually helps.
Just quick implementation of such initializer: https://gist.github.com/PetraVidnerova/c68bd4efc8c349e1d661c67809f3f7f3
The usage will be:
```
  rbflayer = RBFLayer(n_cetners,
                        initializer=InitCentersKMeans(X),
                        betas=betas,
                        input_shape=input_shape)
```
 I plan to include the InitCentersKMeans initializer in my repo rbf_keras, but I haven't test it properly yet.

**Question 2**:  Well, I never met LBFGS applied on RBF weights optimisation. I am interested in what is your motivation for using it.  
Just giving  "LBFGS in Keras" to Google, I found:
https://github.com/keras-team/keras/issues/5085
https://stackoverflow.com/questions/38450729/keras-bfgs-training-using-scipy-minimize
I believe you can find more information and you probably had tried it.
I think you will have to implement your own optimiser in Keras and use it.  However, I have no experience with LBFGS and implementing it in Keras, so I can't help.

**Comment by agcala** [comment]
Sorry but when I run the examples I get an error at

   ` assert shape[1] == self.X.shape[1]`
   ` IndexError: tuple index out of range`
This happens when trying to initialize the widths which is a one-dimensional array. Any idea of how to get wound this?
